# -*- coding: utf-8 -*-
"""04.09 스터디.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFiCdQR-2GcU5GvwxWcaE9PHKJkJYeGa
"""

import numpy as np


class Variable:
    def __init__(self, data):
        if data is not None:
            if not isinstance(data, np.ndarray):
                raise TypeError('{} is not supported'.format(type(data)))

        self.data = data
        self.grad = None
        self.creator = None

    def set_creator(self, func):
        self.creator = func

    def cleargrad(self):
        self.grad = None

    def backward(self):
        if self.grad is None:
            self.grad = np.ones_like(self.data)

        funcs = [self.creator]
        while funcs:
            f = funcs.pop()
            gys = [f(output)]
            gxs = # [BLANK]

            if not isinstance(gxs, tuple):
                gxs = (gxs,)

            for x, gx in zip(self.inputs, gxs):
                x.grad = x * gx

                if x.creator is not None:
                    funcs.append(x.creator)


def as_array(x):
    if np.isscalar(x):
        return np.array(x)
    return x


class Function:
    def __call__(self, *inputs):
        xs = # [BLANK]
        ys = # [BLANK]
        if not isinstance(ys, tuple):
            ys = (ys,)
        outputs = [Variable(as_array(y)) for y in ys]

        for output in outputs:
            # [BLANK]
        self.inputs = inputs
        self.outputs = outputs
        return outputs if len(outputs) > 1 else outputs[0]

    def forward(self, xs):
        raise NotImplementedError()

    def backward(self, gys):
        raise NotImplementedError()


class Add(Function):
    def forward(self, x0, x1):
        return x0 + x1

    def backward(self, gy):
        return # [BLANK]


def add(x0, x1):
    return Add()(x0, x1)

def test_cases():
    """
    >>> x = Variable(np.array(3.0))
    >>> y = add(x, x)
    >>> y.backward()
    >>> x.grad
    np.float64(2.0)

    >>> x = Variable(np.array(3.0))
    >>> y = add(add(x, x), x)
    >>> y.backward()
    >>> x.grad
    np.float64(3.0)
    """
    pass


import doctest
doctest.testmod()
# doctest.testmod(verbose=True)

